### ISSUE TITLE
Menu in Owner Block instead of Main Menu

### ISSUE THREAD

**Issue by rohit1290** [arckinteractive/crushes#1]
I have River Addon Plugin enabled with "Owner Block" option. I don't want the "Crushes" menu to appear among the main menu but instead I want it to appear in the owner block in the sidebar.

How can I do that?

**Comment by rohit1290** [comment]
any help on this?

**Comment by beck24** [comment]
I have no idea what "River Addon" is but you can always use 'register', 'menu:*' plugin hooks to change whatever you want with menus.
